spring.application.name=aiops-backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/aiops_db
spring.datasource.username=apple
spring.datasource.password=23Cb059@@
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=aiops-super-secret-key-for-jwt-token-must-be-at-least-256-bits-long-2024
jwt.expiration=86400000

# ML Service
ml.service.url=http://localhost:5000

# Scheduling
spring.task.scheduling.enabled=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics

spring.main.allow-bean-definition-overriding=true